services:
  - type: web
    name: indianews
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
