# Generated by Django 6.0.4 on 2026-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date (optional)'),
        ),
        migrations.AddField(
            model_name='adspace',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date (optional)'),
        ),
    ]
