# Generated by Django 6.0.5 on 2026-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_adspace_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('client_email', models.CharField(max_length=100, verbose_name='Email')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Phone / WhatsApp')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company / Brand Name')),
                ('position', models.CharField(choices=[('header', 'Header Banner (728×90)'), ('home_top', 'Home Top Banner (970×90)'), ('sidebar_top', 'Sidebar Box (300×250)'), ('sidebar_bottom', 'Sidebar Tall (300×600)'), ('in_content', 'Article Mid (336×280)'), ('footer', 'Footer Banner (728×90)')], max_length=30)),
                ('duration_days', models.IntegerField(choices=[(7, '7 Days'), (15, '15 Days'), (30, '1 Month'), (90, '3 Months')], default=30)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='ad_bookings/', verbose_name='Banner Image')),
                ('banner_url', models.URLField(blank=True, verbose_name='Banner Image URL')),
                ('website_url', models.URLField(verbose_name='Your Website URL')),
                ('ad_title', models.CharField(blank=True, max_length=200, verbose_name='Ad Title / Caption')),
                ('message', models.TextField(blank=True, verbose_name='Additional Message')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ad Booking',
                'verbose_name_plural': 'Ad Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
