# Generated by Django 6.0.5 on 2026-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_adbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='short_news/', verbose_name='Upload Thumbnail'),
        ),
        migrations.AddField(
            model_name='shortnews',
            name='news_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('video', 'Short Video')], default='text', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='shortnews',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video directly', null=True, upload_to='short_videos/', verbose_name='Upload Video (MP4)'),
        ),
        migrations.AddField(
            model_name='shortnews',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube / Instagram Reels / Direct MP4 URL', verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='shortnews',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='content',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Thumbnail Image URL'),
        ),
        migrations.AlterField(
            model_name='shortnews',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
    ]
