# Generated by Django 6.0.5 on 2026-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_shortnews_image_shortnews_news_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaper',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste image URL — use this on Render (uploaded files get deleted on restart)', verbose_name='Newspaper Image URL'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='epaper/%Y/%m/', verbose_name='PDF File (upload)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Paste Google Drive / Dropbox public link', verbose_name='PDF URL (external)'),
        ),
        migrations.AlterField(
            model_name='epaper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='epaper/thumb/', verbose_name='Newspaper Image (upload)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_hi',
            field=models.TextField(verbose_name='Content (Hindi)*'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image_url',
            field=models.URLField(blank=True, verbose_name='Featured Image URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary_hi',
            field=models.TextField(blank=True, verbose_name='Summary (Hindi)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_hi',
            field=models.CharField(max_length=500, verbose_name='Title (Hindi)*'),
        ),
    ]
